# Generated by Django 3.2.20 on 2024-01-13 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=250)),
                ('building', models.CharField(max_length=250)),
                ('landmark', models.CharField(max_length=250)),
                ('town', models.CharField(max_length=250)),
                ('pincode', models.CharField(max_length=250)),
                ('discription', models.CharField(default=1, max_length=2500)),
                ('state', models.CharField(max_length=250)),
                ('profile', models.CharField(max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('age', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=250)),
                ('dob', models.CharField(max_length=250)),
                ('business_name', models.CharField(max_length=250)),
                ('business_type', models.CharField(max_length=250)),
                ('building', models.CharField(max_length=250)),
                ('landmark', models.CharField(max_length=250)),
                ('town', models.CharField(max_length=250)),
                ('pincode', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
                ('contact_info', models.CharField(max_length=2500)),
                ('license_num', models.CharField(max_length=250)),
                ('state_issue', models.CharField(max_length=250)),
                ('insurance_info', models.CharField(max_length=250)),
                ('work_exp', models.CharField(max_length=2500)),
                ('area_expertise', models.CharField(max_length=2500)),
                ('reference', models.CharField(max_length=2500)),
                ('profile', models.CharField(max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dealer_name', models.CharField(max_length=250)),
                ('dob', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=250)),
                ('business_name', models.CharField(max_length=250)),
                ('business_type', models.CharField(max_length=250)),
                ('building', models.CharField(default=1, max_length=2500)),
                ('landmark', models.CharField(default=1, max_length=2500)),
                ('town', models.CharField(default=1, max_length=2500)),
                ('pincode', models.CharField(default=1, max_length=2500)),
                ('state', models.CharField(default=1, max_length=2500)),
                ('reference', models.CharField(max_length=2500)),
                ('profile', models.CharField(max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=250)),
                ('usertype', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=250)),
                ('amount', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=2500)),
                ('payment_status', models.CharField(max_length=250)),
                ('payment_date', models.CharField(max_length=250)),
                ('building', models.CharField(max_length=250)),
                ('landmark', models.CharField(max_length=250)),
                ('town', models.CharField(max_length=250)),
                ('pincode', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
                ('CONTRACTOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreambuilder.contractor')),
                ('DEALER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreambuilder.dealer')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_image', models.CharField(max_length=250)),
                ('room_count', models.CharField(max_length=250)),
                ('bedroom_count', models.CharField(max_length=250)),
                ('bathroom_count', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Vault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=2500)),
                ('discription', models.CharField(max_length=2500)),
                ('CLIENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreambuilder.client')),
            ],
        ),
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=250)),
                ('time', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=250)),
                ('discription', models.CharField(max_length=500)),
                ('addr', models.CharField(default=1, max_length=2500)),
                ('CLIENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreambuilder.client')),
                ('CONTRACTOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreambuilder.contractor')),
            ],
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brick', models.CharField(max_length=250)),
                ('cement', models.CharField(max_length=250)),
                ('paint', models.CharField(max_length=250)),
                ('sand', models.CharField(max_length=250)),
                ('aggrigate', models.CharField(max_length=250)),
                ('steel', models.CharField(max_length=250)),
                ('price', models.CharField(max_length=250)),
                ('CLIENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreambuilder.client')),
                ('CONTRACTOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreambuilder.contractor')),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default=1, max_length=250)),
                ('phase', models.CharField(default=1, max_length=250)),
                ('percentage', models.CharField(default=1, max_length=2500)),
                ('img', models.CharField(default=1, max_length=250)),
                ('pdf', models.CharField(default=1, max_length=2500)),
                ('discription', models.CharField(default=1, max_length=2500)),
                ('sdate', models.CharField(default=1, max_length=2500)),
                ('edate', models.CharField(default=1, max_length=2500)),
                ('USERREQUEST', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dreambuilder.userrequest')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=2500)),
                ('pic', models.CharField(max_length=2500)),
                ('discri', models.CharField(max_length=2500)),
                ('price', models.CharField(max_length=2500)),
                ('status', models.CharField(max_length=2500)),
                ('DEALER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreambuilder.dealer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderSub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qnty', models.CharField(max_length=250)),
                ('ORDER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreambuilder.order')),
                ('PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreambuilder.product')),
            ],
        ),
        migrations.CreateModel(
            name='Gallary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=250)),
                ('discription', models.CharField(max_length=2500)),
                ('CONTRACTOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreambuilder.contractor')),
            ],
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=250)),
                ('discription', models.CharField(max_length=2500)),
                ('income', models.CharField(default=0, max_length=250)),
                ('expense', models.CharField(default=0, max_length=250)),
                ('CONTRACTOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreambuilder.contractor')),
                ('USERREQUEST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreambuilder.userrequest')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=250)),
                ('time', models.CharField(default=1, max_length=250)),
                ('feedback', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=20)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreambuilder.login')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.CharField(max_length=250)),
                ('CLIENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreambuilder.client')),
                ('CONTRACTOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreambuilder.contractor')),
            ],
        ),
        migrations.CreateModel(
            name='DealerComplaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=250)),
                ('time', models.CharField(default=1, max_length=250)),
                ('complainer', models.CharField(max_length=250)),
                ('defendant', models.CharField(max_length=250)),
                ('complain', models.CharField(max_length=2500)),
                ('response', models.CharField(max_length=2500)),
                ('CONTRACTOR', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dreambuilder.contractor')),
                ('DEALER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreambuilder.dealer')),
            ],
        ),
        migrations.AddField(
            model_name='dealer',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreambuilder.login'),
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=250)),
                ('discription', models.CharField(max_length=2500)),
                ('labour_num', models.CharField(max_length=250)),
                ('time', models.CharField(max_length=250)),
                ('consumed', models.CharField(max_length=2500)),
                ('CONTRACTOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreambuilder.contractor')),
            ],
        ),
        migrations.CreateModel(
            name='ContractorReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=250)),
                ('discription', models.CharField(max_length=2500)),
                ('rating', models.CharField(max_length=250)),
                ('CLIENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreambuilder.client')),
                ('CONTRACTOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreambuilder.contractor')),
            ],
        ),
        migrations.CreateModel(
            name='ContractorPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=2500)),
                ('date', models.CharField(max_length=250)),
                ('discription', models.CharField(max_length=2500)),
                ('CLIENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreambuilder.client')),
                ('CONTRACTOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreambuilder.contractor')),
            ],
        ),
        migrations.CreateModel(
            name='ContractorComplaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=250)),
                ('complainer', models.CharField(max_length=250)),
                ('defendant', models.CharField(max_length=250)),
                ('complain', models.CharField(max_length=2500)),
                ('response', models.CharField(max_length=2500)),
                ('CLIENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreambuilder.client')),
                ('CONTRACTOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreambuilder.contractor')),
            ],
        ),
        migrations.AddField(
            model_name='contractor',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreambuilder.login'),
        ),
        migrations.AddField(
            model_name='client',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreambuilder.login'),
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=2500)),
                ('type', models.CharField(max_length=250)),
                ('date', models.CharField(max_length=250)),
                ('CLIENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreambuilder.client')),
                ('CONTRACTOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreambuilder.contractor')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=2500)),
                ('CONTRACTOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreambuilder.contractor')),
                ('PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreambuilder.product')),
            ],
        ),
    ]
