"""dreambuilders URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path
from dreambuilder import views

urlpatterns = [
    path('',views.logins),
    path('loginpost',views.loginpost),
    path('ggg',views.logout),
    path('home',views.home),
    path('view_material',views.view_material),
    path('add_material',views.add_material),
    path('add_material_post',views.add_material_post),
    path('update_material/<id>',views.update_material),
    path('update_material_post/<id>',views.update_material_post),
    path('delete_material_post/<id>',views.delete_material_post),
    path('add_plan',views.add_plan),
    path('add_plan_post',views.add_plan_post),
    path('view_plan',views.view_plan),
    path('update_plan/<id>',views.update_plan),
    path('update_plan_post/<id>',views.update_plan_post),
    path('delete_plan_post/<id>',views.delete_plan_post),
    path('view_contractor_appproval',views.view_contractor_appproval),
    path('view_contractor_appproved',views.view_contractor_appproved),
    path('view_dealer_appproval',views.view_dealer_appproval),
    path('view_dealer_appproved',views.view_dealer_appproved),
    path('view_client',views.view_client),
    path('view_dealer_complaint',views.view_dealer_complaint),
    path('view_contractor_complaint',views.view_contractor_complaint),
    path('feedback',views.feedback),
    path('view_feedback', views.view_feedback),
    path('changepass', views.changepass),
    path('hhhh', views.changepass_post),
    # ==================================================================

    path('contractor_plan', views.contractor_plan),
    path('contractor_plan_post', views.contractor_plan_post),
    path('addcontractor',views.addcontractor),
    path('edit_contractor',views.edit_contractor),
    path('edit_contractor_post',views.edit_contractor_post),
    path('approve_contractor/<id>',views.approve_contractor),
    path('dealer_reject/<id>',views.dealer_reject),
    path('contractor_reject/<id>',views.contractor_reject),
    path('block_contractor/<id>',views.block_contractor),
    path('unblock_contractor/<id>',views.unblock_contractor),
    path('approve_dealer/<id>',views.approve_dealer),
    path('block_dealer/<id>', views.block_dealer),
    path('unblock_dealer/<id>',views.unblock_dealer),
    path('block_client/<id>', views.block_client),
    path('unblock_client/<id>', views.unblock_client),
    path('contractor_post',views.contractor_post),
    path('client',views.client),
    path('client_post',views.client_post),
    path('view_contractor_review',views.view_contractor_review),
    path('daily_report/<id>',views.daily_report),
    path('daily_report_post/<id>',views.daily_report_post),
    path('document',views.document),
    path('document_post',views.document_post),
    path('feedback',views.feedback),
    path('feedback_post',views.feedback_post),
    path('finance/<id>',views.finance),
    path('finance_post/<id>',views.finance_post),
    path('update_finance/<id>',views.update_finance),
    path('update_finance_post/<id>',views.update_finance_post),
    path('delete_finance/<id>',views.delete_finance),
    path('gallery',views.gallery),
    path('gallery_post',views.gallery_post),
    path('progress',views.progress),
    path('progress_post',views.progress_post),
    path('view_user_request',views.view_user_request),
    path('dealerchangepass',views.dealerchangepass),
    path('dealerchangepass_post',views.dealerchangepass_post),
    path('view_order',views.view_order),
    path('order_sub',views.order_sub),
    path('order_sub_post',views.order_sub_post),
    path('chatt/<u>',views.chatt),
    path('chatsnd/<u>',views.chatsnd),
    path('chatrply',views.chatrply),
    path('contractor_changepass',views.contractor_changepass),
    path('contrctor_changepass_post',views.contrctor_changepass_post),
    path('view_gallery',views.view_gallery),
    path('edit_gallery/<id>', views.edit_gallery),
    path('edit_gallery_post/<id>', views.edit_gallery_post),
    path('remove_gallery/<id>',views.remove_gallery),
    path('adddealer',views.adddealer),
    path('dealer_post',views.dealer_post),
    path('dealer_complaint',views.dealer_complaint),
    path('dealer_product_search',views.dealer_product_search),
    path('dealer_complaint_post',views.dealer_complaint_post),
    path('feedback',views.feedback),
    path('feedback_post',views.feedback_post),
    path('confirm_pass',views.confirm_pass),
    path('confirm_pass_post',views.confirm_pass_post),
    path('view_user_approved',views.view_user_approved),
    path('approve_contractor_user/<id>', views.approve_contractor_user),
    path('reject_contractor_user/<id>', views.reject_contractor_user),
    path('vault/<id>', views.vault),
    path('vault_post/<id>', views.vault_post),
    path('purchase', views.purchase),
    path('product_search',views.product_search),
    path('addcart/<id>',views.addcart),
    path('addcart_post/<id>',views.addcart_post),
    path('cart',views.cart),
    path('remove_cart/<id>',views.remove_cart),
    path('edit_cart/<id>',views.edit_cart),
    path('edit_cart_post/<id>',views.edit_cart_post),
    path('delivery_address', views.delivery_address),
    path('delivery_address_post', views.delivery_address_post),
    path('view_order_status', views.view_order_status),
    path('more_order_status/<id>',views.more_order_status),
    path('contractor_order_manager',views.contractor_order_manager),
    path('contractor_order_manager_post',views.contractor_order_manager_post),
    path('addprogress/<id>',views.addprogress),
    path('addprogress_post/<id>',views.addprogress_post),
    path('addprogress_post2/<id>',views.addprogress_post2),
    path('view_vault/<id>', views.view_vault),
    path('edit_dealer',views.edit_dealer),
    path('edit_dealer_post',views.edit_dealer_post),
    path('view_contractor_product_request',views.view_contractor_product_request),
    path('view_contractor_product_request_sub/<id>',views.view_contractor_product_request_sub),
    path('dealer_feedback',views.dealer_feedback),
    path('dealer_feedback_post',views.dealer_feedback_post),
    path('approve_contractor_request/<id>', views.approve_contractor_request),
    path('reject_contractor_request/<id>', views.reject_contractor_request),
    path('product_purchase', views.product_purchase),
    path('add_product',views.add_product),
    path('add_product_post',views.add_product_post),
    path('edit_product/<id>',views.edit_product),
    path('edit_product_post/<id>',views.edit_product_post),
    path('remove_product/<id>',views.remove_product),
    path('view_contractor_approved_product',views.view_contractor_approved_product),
    path('view_contractor_approved_product_sub/<id>',views.view_contractor_approved_product_sub),
    path('view_daily_report/<id>', views.view_daily_report),
    path('remove_daily_report/<id>',views.remove_daily_report),
    path('update_daily_report/<id>',views.update_daily_report),
    path('update_daily_report_post/<id>',views.update_daily_report_post),
    path('and_login', views.and_login),
    path('and_contractor_search', views.and_contractor_search),
    path('and_contractor_all', views.and_contractor_all),
    path('and_contractor_gallery', views.and_contractor_gallery),
    path('and_contractor_review', views.and_contractor_review),
    path('add_chat', views.add_chat),
    path('view_chat', views.view_chat),
    path('edit_userregistration', views.edit_userregistration),
    path('userregistration', views.userregistration),
    path('and_view_profile', views.and_view_profile),
    path('and_view_plan', views.and_view_plan),
    path('and_view_plan_search', views.and_view_plan_search),
    path('and_send_feedback', views.and_send_feedback),
    path('and_frgt', views.and_frgt),
    path('and_send_request', views.and_send_request),
    path('and_view_request', views.and_view_request),
    path('and_send_complaint', views.and_send_complaint),
    path('and_upload_document', views.and_upload_document),
    path('and_view_document', views.and_view_document),
    path('and_progress', views.and_progress),
    path('and_change_password', views.and_change_password),
    path('and_send_rating', views.and_send_rating),
    path('contractor_complaint/<id>', views.contractor_complaint),
    path('contractor_complaint_post/<id>', views.contractor_complaint_post),

    #######     checking
    path('boq1', views.boq1),
    path('boq1_post', views.boq1_post),
    path('start_page',views.start_page),
    path('page1post',views.page1post),
    path('page2post',views.page2post),
    path('door1_post',views.door1_post),
    path('door2_post',views.door2_post),
    path('windows1_post',views.windows1_post),
    path('window2_post',views.window2_post),
    path('vent1_post',views.vent1_post),
    path('vent2_post',views.vent2_post),
    path('lintel_post',views.lintel_post),
    path('slab_post',views.slab_post),
]
